"""empty message

Revision ID: c9e8f5a547b9
Revises: 01045c02f2d7
Create Date: 2023-07-31 11:43:59.308621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9e8f5a547b9'
down_revision = '01045c02f2d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('kitchen_side')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kitchen_side',
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name='kitchen_side_item_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='kitchen_side_order_id_fkey'),
    sa.PrimaryKeyConstraint('order_id', 'item_id', name='kitchen_side_pkey')
    )
    op.drop_table('order_items')
    # ### end Alembic commands ###
